name: Сборка и выгрузка

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Сборка
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm i
      - run: npm run prod
        
      - name: 📂 Выгрузка файлов на удаленный сервер
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: hostdl.beget.tech
          username: hostdl_wp
          password: BV1T*jBn
          local-dir: dist/
          exclude: |
            /.git*
            /.git*/
            /.github*
            /.github*/
            /.vscode/
            /app/
            /node_modules/
            /gulpfile.js*
            /package.json*
