on: push

name: telegram message

jobs:

  web-deploy:

    name: Build

    runs-on: ubuntu-latest

    steps:

    - name: Отправка сообщения в группу telegram
      uses: colutius/Telegram-Msg@main
      with:
        chatid: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        disable_notification: true
        message: |
          Commit: ${{ github.event.commits[0].message }}
          Branch: #${{ github.ref_name }}
          Author: #${{ github.actor }} 
        button: true
        button_name: Посмотреть изменения
        button_url: https://github.com/${{ github.repository }}/commit/${{github.sha}}
        is_notify: false
        is_preview: false
